export const initialTestimonials = [
  {
    id: 1,
    name: "Sarah Khan",
    role: "Python Developer",
    image: "/assets/Avatar2.png",
    text: "The Python course was incredibly well-structured and the instructors were always available to help. I landed my first developer job within a month of completing the course!",
    rating: 5,
  },
  {
    id: 2,
    name: "Ahmed Raza",
    role: "Backend Developer",
    image: "/assets/Avatar5.png",
    text: "The advanced Python course gave me the skills I needed to build complex applications. The hands-on projects were particularly valuable for my career growth.",
    rating: 4,
  },
  {
    id: 3,
    name: "Angela Lee",
    role: "Full Stack Developer",
    image: "/assets/Avatar9.png",
    text: "I came in with zero programming experience, and now I'm working as a full-stack developer. The curriculum is comprehensive and the community support is amazing.",
    rating: 5,
  },
  {
    id: 4,
    name: "Hassan Ali",
    role: "Data Analyst",
    image: "/assets/Avatar7.png",
    text: "The data analysis module transformed my career. Learning pandas and numpy with real-world projects was a game-changer for me.",
    rating: 5,
  },
  {
    id: 5,
    name: "Maria Syed",
    role: "Web Developer",
    image: "/assets/Avatar3.png",
    text: "The web development track was fantastic. Building a full e-commerce site as a project gave me the confidence to freelance successfully.",
    rating: 4,
  },
  {
    id: 6,
    name: "Omar Farooq",
    role: "Software Engineer",
    image: "/assets/Avatar1.png",
    text: "The capstone project tied everything together perfectly. I now work at a tech startup, thanks to the skills I gained here.",
    rating: 5,
  },
];
